### ISSUE TITLE
Sometimes doesn't work. 

### ISSUE THREAD

**Issue by nikhilbadyal** [pszklarska/FlutterPubVersionChecker#45] opened 2021-12-11 07:20 UTC
I think title is clear enough. 
Please see the attached video. From the internet speed meter on the side it's clear that extension is checking for update but it isn't showing me update . 

I would like to mention one more issue. Sometimes it throttles the UI. I have to kill the IDE from task manager. Maybe multiple request at same time? IDE doesn't accepts any input , just hangs. Kill the IDE is the only solution.

https://user-images.githubusercontent.com/59223300/145668156-c30e294e-9a2f-44b0-bd38-0eac7115f8d7.mp4

**Comment by pszklarska** [comment] 2021-12-12 05:23
Hi @nikhilbadyal! Thank you for reporting that issue. The cause is the same as in issue #43 (pub.dev API had slightly changed). I'm working on the solution right now and it should be published within the next few days. I'm closing this issue as a duplicate.

**Closed by pszklarska** 2021-12-12 05:23 UTC
