### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bhanuka96** [pszklarska/FlutterPubVersionChecker#43] opened 2021-12-06 03:37 UTC
Plugin is not working on my Android Studio

flutter doctor

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
    en-LK)
    • Flutter version 2.5.3 at /Users/bhanukaisuru/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bhanukaisuru/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • PRA LX2 (mobile) • 6MU7N17A12000618 • android-arm64  • Android 8.0.0 (API
      26)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      96.0.4564.55

• No issues found!
```

**Comment by pszklarska** [comment] 2021-12-08 08:01
Hi @bhanuka96  thanks for reporting that! What's the issue with the plugin not working? Do you not see the highlights in the `pubpsec.yaml` or is there any error reported?

**Comment by bhanuka96** [comment] 2021-12-08 08:09
@pszklarska Yes, it isn't highlighted in the yaml file

**Comment by zhenyakr** [comment] 2021-12-08 21:38
Do you have Mac OS support?
On my PC with window OS, the plugin works, but installed it on the Mac, and does not highlight the versions for updating
p.s.
- android studio updated and rebooted
- pc rebooted
- flutter pub get wrote

**Comment by wz366** [comment] 2021-12-09 07:15
Same here, not working in Android studio, using a Mac

**Comment by bhanuka96** [comment] 2021-12-09 07:26
@zhenyakr Mac Intel

Latest Android Studio Android Studio Arctic Fox | 2020.3.1 Patch 4

**Comment by zhenyakr** [comment] 2021-12-09 08:19
I have a MacBook with M1
Latest Android Studio Android Studio Arctic Fox | 2020.3.1 Patch 4

**Comment by WingCH** [comment] 2021-12-09 11:25
same here

```
Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 10
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains, com.mallowigi, com.tao.getx, Dart, com.thoughtworks.gauge, org.jetbrains.kotlin, io.flutter, com.chrisrm.idea.MaterialThemeUI, pl.pszklarska.pubversionchecker, org.intellij.plugins.markdown
```

**Comment by rebaz94** [comment] 2021-12-09 12:19
Same here, not working in Android studio using Mac

```
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 3966M
Cores: 4
Registry: documentation.show.toolbar=true, ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: Statistic, co.anbora.labs.firebase-syntax-highlighting, com.thoughtworks.gauge, org.intellij.plugins.markdown, com.intellij.marketplace, org.jetbrains.kotlin, com.spidev.pubassist, Dart, io.flutter, com.localizely.flutter-intl
```

**Comment by pszklarska** [comment] 2021-12-10 11:34
Hi everyone, thanks for reporting that issue! It looks like it's caused by the recent changes in the pub.dev API. I'm gonna fix it and release a new version tomorrow.

**Comment by pszklarska** [comment] 2021-12-12 08:44
Hey! That issue is resolved in the newest version: https://github.com/pszklarska/FlutterPubVersionChecker/releases/tag/v1.3.2
It should be available to download within the next few days 👍 

I'm closing this issue for now, feel free to re-open it if you still see it after the upgrade.

**Closed by pszklarska** 2021-12-12 08:44 UTC
Labels: question

**Comment by wz366** [comment] 2021-12-12 08:46
Thanks @pszklarska for the quick update!
